# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  # Not working. See: https://github.com/dependabot/dependabot-core/issues/13880
  # - package-ecosystem: "bazel" # zizmor: ignore[dependabot-cooldown] bazel ecosystem does not support
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   groups:
  #     rules-python:
  #       patterns:
  #         - "rules_python*"
  #   # cooldown:
  #   #   default-days: 7

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
