[workspace]
[package]
name = "all_crate_deps"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "/dev/null"

[dependencies]
ar = "0.9.0"
clap = { version = "4.5.13", features = ["derive"] }
